### ISSUE TITLE
工程运行报错

### ISSUE THREAD

**Issue by hanlzt** [WinterChenS/springboot2-mybatis-demo#2]
Failed to bind properties under 'spring.datasource.type' to java.lang.Class<javax.sql.DataSource>:

    Property: spring.datasource.type
    Value: com.alibaba.druid.pool.DruidDataSource
    Origin: class path resource [application.yml]:8:15
    Reason: No converter found capable of converting from type [java.lang.String] to type [java.lang.Class<javax.sql.DataSource>]

Action:

Update your application's configuration

在2.0.1下运行报上面的错误，你确定你试过吗？

**Comment by WinterChenS** [comment]
确定
